update .yml

diff --git a/.github/workflows/azure.yml b/.github/workflows/azure.yml
--- a/.github/workflows/azure.yml
+++ b/.github/workflows/azure.yml
@@ -37,13 +37,13 @@ jobs:
         name: test-results
         path: TestResults
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1.9.1
-      if: success() || failure()
-      with:
-        name: NUnit Tests
-        path: TestResults/*.trx
-        reporter: dotnet-trx
+    # - name: Test Report
+    #   uses: dorny/test-reporter@v1.9.1
+    #   if: success() || failure()
+    #   with:
+    #     name: NUnit Tests
+    #     path: TestResults/*.trx
+    #     reporter: dotnet-trx
 
   base_branch_cov:
     runs-on: ubuntu-latest
@@ -101,8 +101,8 @@ jobs:
       - name: Test
         run: dotnet test --no-build
 
-      - name: Collect Coverage
-        run: coverlet ./UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --targetargs "test --no-build" --format lcov --output ./lcov.info
+      # - name: Collect Coverage
+      #   run: coverlet ./UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --targetargs "test --no-build" --format lcov --output ./lcov.info
 
       - name: Download base branch coverage report
         uses: actions/download-artifact@v4
@@ -151,7 +151,7 @@ jobs:
     - name: Deploy to Azure Web App
       uses: azure/webapps-deploy@v3
       with:
-        app-name: 'CSCE590'  # Replace with your actual Azure Web App name
+        app-name: 'Certatheon'
         slot-name: 'Production'
         package: ${{ github.workspace }}/publish
         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE3F80DD1F3C46AFA4474BC175935A84 }}
